name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PACKER_VERSION: "1.9.4"

jobs:
  analyze:
    name: Analyze the Packer scripts
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Packer CLI
        uses: hashicorp/setup-packer@main
        with:
          version: "${{ env.PACKER_VERSION }}"

      - name: Run Packer init
        run: packer init .

      - name: Run Packer format check
        run: packer fmt -check -recursive .

      - name: Run Packer validate check
        run: packer validate -syntax-only .
